
pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'docker build -t backend:latest ./docker/backend'
      }
    }
    stage('Deploy') {
      steps {
        sh 'kubectl apply -f k8s/backend-deployment.yaml'
      }
    }
  }
}
