replicaCount: 1

image:
  repository: YOURAWSID.dkr.ecr.us-east-1.amazonaws.com/videotube-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: postgres-credentials
        key: POSTGRES_HOST
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: postgres-credentials
        key: POSTGRES_DB
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: postgres-credentials
        key: POSTGRES_USER
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-credentials
        key: POSTGRES_PASSWORD

env:
  - name: REDIS_HOST
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: REDIS_HOST
