replicaCount: 1

image:
  repository: YOURAWSID.dkr.ecr.us-east-1.amazonaws.com/videotube-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
